-- MySQL Script generated by MySQL Workbench
-- Tue Jul 10 16:19:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotify` ;

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` DEFAULT CHARACTER SET utf8 ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`tracker` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `minutes_played` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL,
  `songs_played` INT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `music_platform` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

CREATE USER 'appuser'@'localhost' IDENTIFIED BY 'appuser';

GRANT SELECT ON TABLE `spotify`.* TO 'appuser'@'localhost';
GRANT SELECT, INSERT, TRIGGER ON TABLE `spotify`.* TO 'appuser'@'localhost';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `spotify`.* TO 'appuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `spotify`.`tracker`
-- -----------------------------------------------------
START TRANSACTION;
USE `spotify`;
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`, `songs_played`, `genre`, `music_platform`) VALUES (1, 24, '2018/07/01', 6, 'Rock', 'Spotify');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`, `songs_played`, `genre`, `music_platform`) VALUES (2, 84, '2018/06/03', 22, 'Electronic', 'Spotify');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`, `songs_played`, `genre`, `music_platform`) VALUES (3, 49, '2018/03/02', 10, 'Classical', 'Tidal');

COMMIT;

