-- MySQL Script generated by MySQL Workbench
-- Mon Jul  9 14:49:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotify` ;

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` DEFAULT CHARACTER SET utf8 ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`tracker` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `minutes_played` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `spotify`.`tracker`
-- -----------------------------------------------------
START TRANSACTION;
USE `spotify`;
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`) VALUES (1, 22, '2018/07/02');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`) VALUES (2, 45, '2018/06/29');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`) VALUES (3, 55, '2018/06/24');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`) VALUES (4, 2, '2018/05/02');
INSERT INTO `spotify`.`tracker` (`id`, `minutes_played`, `date`) VALUES (5, 58, '2018/04/24');

COMMIT;

